#ifndef ESP32_CONTROLLER_DEFS_H
#define ESP32_CONTROLLER_DEFS_H

// USB SERIAL SPEED (7.3728*1e6/2^N)
// #define SERIAL_BAUDRATE 115200
// #define SERIAL_BAUDRATE 230400
// #define SERIAL_BAUDRATE 460800
#define SERIAL_BAUDRATE 921600
// #define SERIAL_BAUDRATE 1843200

// INTER CPU MESG QUEUE SIZE
#define QUEUE_SIZE 1

// LORA SENDER SLOW DOWN 
// (do not send more than one msg every LORA_SLOWDOWN ms)
#define LORA_SLOWDOWN 100L

// MAGIC NUMBER TO CHECK FOR USB ERRORS
#define MAGIC_NUMBER 0xCA

#endif /* ESP32_CONTROLLER_DEFS_H */
